services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "5002:5002"
    environment:
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - db

  transaction_service:
    build:
      context: ./transaction_service
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET_KEY=your_secret_key
      - BUDGET_SERVICE_URL=http://budget_service:5003
    depends_on:
      - db
      - budget_service

  budget_service:
    build:
      context: ./budget_service
    ports:
      - "5003:5003"
    environment:
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: